create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Coder',
  username text unique,
  avatar_url text,
  daily_goal_xp integer not null default 50 check (daily_goal_xp between 10 and 500),
  time_zone text not null default 'UTC',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  language text not null,
  accent text,
  sort_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.units (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  slug text not null,
  title text not null,
  description text not null default '',
  theme text,
  sort_order integer not null default 0,
  is_published boolean not null default false,
  unique (course_id, slug)
);

create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  unit_id uuid not null references public.units(id) on delete cascade,
  slug text not null unique,
  title text not null,
  subtitle text not null default '',
  lesson_type text not null default 'lesson'
    check (lesson_type in ('lesson', 'checkpoint', 'project', 'practice')),
  icon text,
  xp_reward integer not null default 20 check (xp_reward >= 0),
  duration_minutes integer not null default 5 check (duration_minutes > 0),
  sort_order integer not null default 0,
  is_published boolean not null default false
);

create table if not exists public.exercises (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  exercise_key text not null unique,
  exercise_type text not null
    check (exercise_type in ('choice', 'text', 'code', 'order', 'debug')),
  eyebrow text not null default '',
  prompt text not null,
  code_snippet text,
  options jsonb,
  placeholder text,
  hint text,
  explanation text,
  sort_order integer not null default 0,
  is_published boolean not null default false
);

create table if not exists private.exercise_answers (
  exercise_id uuid primary key references public.exercises(id) on delete cascade,
  accepted_answers jsonb not null,
  correct_feedback text not null,
  incorrect_feedback text not null
);

create table if not exists public.user_lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  status text not null default 'available'
    check (status in ('locked', 'available', 'in_progress', 'completed')),
  attempts integer not null default 0 check (attempts >= 0),
  best_score numeric(5,2) not null default 0 check (best_score between 0 and 100),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

create table if not exists public.exercise_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_id uuid not null references public.exercises(id) on delete cascade,
  submitted_answer jsonb not null,
  is_correct boolean,
  session_id uuid,
  attempted_at timestamptz not null default now()
);

create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null check (amount <> 0),
  event_type text not null,
  lesson_id uuid references public.lessons(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_tutor_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_slug text not null,
  exercise_key text not null,
  mode text not null check (mode in ('hint', 'explain', 'example')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists time_zone text not null default 'UTC';
alter table public.exercise_attempts add column if not exists session_id uuid;

create index if not exists units_course_sort_idx on public.units(course_id, sort_order);
create index if not exists lessons_unit_sort_idx on public.lessons(unit_id, sort_order);
create index if not exists exercises_lesson_sort_idx on public.exercises(lesson_id, sort_order);
create index if not exists lesson_progress_user_idx on public.user_lesson_progress(user_id, status);
create index if not exists exercise_attempts_user_idx on public.exercise_attempts(user_id, attempted_at desc);
create index if not exists exercise_attempts_session_idx on public.exercise_attempts(user_id, session_id, attempted_at desc);
create index if not exists xp_events_user_idx on public.xp_events(user_id, created_at desc);
create index if not exists ai_tutor_events_user_idx on public.ai_tutor_events(user_id, created_at desc);
create unique index if not exists xp_events_lesson_completion_unique
on public.xp_events(user_id, lesson_id, event_type)
where event_type = 'lesson_completed';

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.units enable row level security;
alter table public.lessons enable row level security;
alter table public.exercises enable row level security;
alter table public.user_lesson_progress enable row level security;
alter table public.exercise_attempts enable row level security;
alter table public.xp_events enable row level security;
alter table public.ai_tutor_events enable row level security;

create policy "published courses are readable"
on public.courses for select
to anon, authenticated
using (is_published);

create policy "published units are readable"
on public.units for select
to anon, authenticated
using (
  is_published
  and exists (
    select 1 from public.courses c
    where c.id = units.course_id and c.is_published
  )
);

create policy "published lessons are readable"
on public.lessons for select
to anon, authenticated
using (
  is_published
  and exists (
    select 1
    from public.units u
    join public.courses c on c.id = u.course_id
    where u.id = lessons.unit_id
      and u.is_published
      and c.is_published
  )
);

create policy "published exercises are readable"
on public.exercises for select
to anon, authenticated
using (
  is_published
  and exists (
    select 1
    from public.lessons l
    join public.units u on u.id = l.unit_id
    join public.courses c on c.id = u.course_id
    where l.id = exercises.lesson_id
      and l.is_published
      and u.is_published
      and c.is_published
  )
);

create policy "users can read own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "users can update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "users can read own progress"
on public.user_lesson_progress for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can read own attempts"
on public.exercise_attempts for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can read own xp"
on public.xp_events for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users can read own tutor usage"
on public.ai_tutor_events for select
to authenticated
using ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.courses, public.units, public.lessons, public.exercises to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, username, avatar_url, daily_goal_xp, time_zone) on public.profiles to authenticated;
grant select on public.user_lesson_progress to authenticated;
grant select on public.exercise_attempts to authenticated;
grant select on public.xp_events to authenticated;
grant select on public.ai_tutor_events to authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), 'Coder')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;
revoke all on function private.handle_new_user() from anon;
revoke all on function private.handle_new_user() from authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

with new_course as (
  insert into public.courses (
    slug, title, description, language, accent, sort_order, is_published
  )
  values (
    'python-foundations',
    'Python Foundations',
    'Learn the building blocks of Python through short interactive lessons.',
    'Python',
    '#5b52e8',
    1,
    true
  )
  on conflict (slug) do update
    set title = excluded.title,
        description = excluded.description,
        language = excluded.language,
        accent = excluded.accent,
        sort_order = excluded.sort_order,
        is_published = excluded.is_published
  returning id
),
course_row as (
  select id from new_course
  union all
  select id from public.courses where slug = 'python-foundations'
  limit 1
),
new_unit as (
  insert into public.units (
    course_id, slug, title, description, theme, sort_order, is_published
  )
  select
    id,
    'beginner-meadow',
    'Beginner Meadow',
    'Your first steps into Python.',
    'meadow',
    1,
    true
  from course_row
  on conflict (course_id, slug) do update
    set title = excluded.title,
        description = excluded.description,
        theme = excluded.theme,
        sort_order = excluded.sort_order,
        is_published = excluded.is_published
  returning id
),
unit_row as (
  select id from new_unit
  union all
  select u.id
  from public.units u
  join course_row c on c.id = u.course_id
  where u.slug = 'beginner-meadow'
  limit 1
)
insert into public.lessons (
  unit_id, slug, title, subtitle, lesson_type, icon, xp_reward, duration_minutes, sort_order, is_published
)
select id, 'hello-world', 'Hello, Python!', 'Meet your first line of code', 'lesson', '👋', 20, 4, 1, true from unit_row
union all
select id, 'variables', 'Variables', 'Give your data a name', 'lesson', '📦', 25, 6, 2, true from unit_row
union all
select id, 'data-types', 'Data Types', 'Strings, numbers and booleans', 'lesson', '🧩', 25, 6, 3, true from unit_row
union all
select id, 'operators', 'Operators', 'Make values work together', 'lesson', '➕', 30, 7, 4, true from unit_row
union all
select id, 'checkpoint-1', 'Trail Checkpoint', 'Prove what you remember', 'checkpoint', '⭐', 50, 8, 5, true from unit_row
union all
select id, 'conditions', 'Conditions', 'Teach code how to decide', 'lesson', '🔀', 30, 7, 6, true from unit_row
union all
select id, 'loops', 'Loops', 'Repeat without repeating yourself', 'lesson', '🔁', 35, 8, 7, true from unit_row
union all
select id, 'functions', 'Functions', 'Build reusable blocks', 'lesson', '🛠️', 40, 9, 8, true from unit_row
union all
select id, 'mini-project', 'Mini Project', 'Build a tiny quiz game', 'project', '🚀', 100, 15, 9, false from unit_row
on conflict (slug) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'hello-print-choice', 'choice', 'Pick the code',
  'Which line tells Python to display Hello, coder!?',
  null,
  '["print(\"Hello, coder!\")","show(\"Hello, coder!\")","say(\"Hello, coder!\")","output = \"Hello, coder!\""]'::jsonb,
  null,
  'Look for Python''s built-in print function.',
  'print() displays values in Python.',
  1, true
from public.lessons l where l.slug = 'hello-world'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'hello-fill-print', 'text', 'Fill the blank',
  'Complete the function name.',
  '____("I can code!")',
  'Type the missing word',
  'It starts with p.',
  'The print function sends text to the output.',
  2, true
from public.lessons l where l.slug = 'hello-world'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'hello-output', 'choice', 'Predict the output',
  'What does this code display?',
  'print("Python is fun")',
  '["Python is fun","\"Python is fun\"","print","Nothing"]'::jsonb,
  'Focus on the text inside the quotation marks.',
  'Quotation marks define the string but are not printed.',
  3, true
from public.lessons l where l.slug = 'hello-world'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'variable-create', 'choice', 'Choose the variable',
  'Which line creates a variable named score with the value 10?',
  '["score = 10","10 = score","score == 10","score = \"ten\""]'::jsonb,
  'Use variable_name = value.',
  'Assignment stores the value on the right in the name on the left.',
  1, true
from public.lessons l where l.slug = 'variables'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'variable-name', 'text', 'Fill the blank',
  'Create a variable named lives with the value 7. Type only the missing name.',
  '_____ = 7',
  'Variable name',
  'The prompt tells you the exact variable name.',
  'The variable name labels the value so it can be reused later.',
  2, true
from public.lessons l where l.slug = 'variables'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'variable-output', 'choice', 'Predict the output',
  'What will Python display?',
  E'points = 4\npoints = points + 3\nprint(points)',
  '["4","7","43","points"]'::jsonb,
  'Start at 4, then follow the update.',
  'The second line adds 3 and stores the new value back in points.',
  3, true
from public.lessons l where l.slug = 'variables'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'variable-code', 'code', 'Write code',
  'Create a variable named language and store the text Python in it.',
  'language = "Python"',
  'Use name = "text".',
  'Strings are placed inside quotation marks.',
  4, true
from public.lessons l where l.slug = 'variables'
on conflict (exercise_key) do nothing;


insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'type-string', 'choice', 'Name the type',
  'What data type is the value stored in name?',
  'name = "Ada"',
  '["String","Integer","Boolean","Float"]'::jsonb,
  null,
  'Quotation marks mean text.',
  'Text values are strings.',
  1, true
from public.lessons l where l.slug = 'data-types'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'type-integer', 'choice', 'Name the type',
  'What data type is 16 in this code?',
  'age = 16',
  '["Integer","String","Float","Boolean"]'::jsonb,
  'Whole numbers are integers.',
  '16 has no decimal point, so it is an integer.',
  2, true
from public.lessons l where l.slug = 'data-types'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'type-boolean', 'text', 'Fill the blank',
  'Complete the boolean value so is_ready means yes.',
  'is_ready = _____',
  'Boolean value',
  'Python uses True with a capital T.',
  'Booleans represent True or False.',
  3, true
from public.lessons l where l.slug = 'data-types'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'type-float-code', 'code', 'Write code',
  'Create a variable named temperature and store the decimal number 24.5.',
  'temperature = 24.5',
  'Use a normal variable assignment.',
  'Numbers with decimal points are floats.',
  4, true
from public.lessons l where l.slug = 'data-types'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'operator-add', 'choice', 'Predict the result',
  'What value is stored in total?',
  'total = 5 + 3',
  '["8","53","2","15"]'::jsonb,
  'The + operator adds the numbers.',
  '5 + 3 evaluates to 8.',
  1, true
from public.lessons l where l.slug = 'operators'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'operator-compare', 'choice', 'True or false',
  'What does this comparison produce?',
  '7 > 4',
  '["True","False","7","4"]'::jsonb,
  'Ask whether 7 is greater than 4.',
  'Comparison operators produce a boolean result.',
  2, true
from public.lessons l where l.slug = 'operators'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'operator-multiply', 'text', 'Fill the operator',
  'Which Python operator multiplies two numbers?',
  '6 ___ 4',
  'Operator',
  'Python uses an asterisk.',
  'The * symbol is Python''s multiplication operator.',
  3, true
from public.lessons l where l.slug = 'operators'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'operator-code', 'code', 'Write code',
  'Create a variable named total that stores 6 multiplied by 4.',
  'total = 6 * 4',
  'Combine assignment with the multiplication operator.',
  'The expression 6 * 4 evaluates before being stored in total.',
  4, true
from public.lessons l where l.slug = 'operators'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'checkpoint-print', 'choice', 'Checkpoint',
  'Which line correctly displays the word Ready?',
  '["print(\"Ready\")","display(\"Ready\")","Ready = print","print = \"Ready\""]'::jsonb,
  'Use Python''s normal output function.',
  'print() displays a value.',
  1, true
from public.lessons l where l.slug = 'checkpoint-1'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'checkpoint-variable', 'choice', 'Checkpoint',
  'Which line stores 12 in a variable named score?',
  '["score = 12","12 = score","score == 12","score = \"12 points\""]'::jsonb,
  'Use variable_name = value.',
  'Assignment places the value on the right into the variable on the left.',
  2, true
from public.lessons l where l.slug = 'checkpoint-1'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'checkpoint-type', 'choice', 'Checkpoint',
  'What type of value is 3.5?',
  '["Float","Integer","String","Boolean"]'::jsonb,
  'Look at the decimal point.',
  'A decimal number is a float.',
  3, true
from public.lessons l where l.slug = 'checkpoint-1'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'checkpoint-operator', 'choice', 'Checkpoint',
  'What does this expression evaluate to?',
  '10 - 3',
  '["7","13","103","30"]'::jsonb,
  'Evaluate the subtraction.',
  '10 - 3 equals 7.',
  4, true
from public.lessons l where l.slug = 'checkpoint-1'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'checkpoint-code', 'code', 'Final challenge',
  'Create score with the value 12, then print score on the next line.',
  E'score = 12\nprint(score)',
  'Write the assignment first, then print the variable.',
  'This combines variables with output.',
  5, true
from public.lessons l where l.slug = 'checkpoint-1'
on conflict (exercise_key) do nothing;


insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'condition-syntax', 'choice', 'Choose the syntax',
  'Which line starts a valid Python condition?',
  '["if score > 10:","if score > 10","when score > 10:","if (score > 10) then"]'::jsonb,
  'Python if statements end the condition line with a colon.',
  'An if statement begins with if and ends its condition line with a colon.',
  1, true
from public.lessons l where l.slug = 'conditions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'condition-output', 'choice', 'Predict the output',
  'What will this code display?',
  E'temperature = 30\nif temperature > 25:\n    print("Warm")',
  '["Warm","30","True","Nothing"]'::jsonb,
  'Check whether 30 makes the condition true.',
  'Because 30 is greater than 25, the indented print statement runs.',
  2, true
from public.lessons l where l.slug = 'conditions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'condition-else', 'text', 'Fill the keyword',
  'Which keyword handles the other case?',
  E'if lives > 0:\n    print("Keep going")\n____:\n    print("Game over")',
  'Python keyword',
  'Think of the keyword that means otherwise.',
  'else runs when the earlier if condition is false.',
  3, true
from public.lessons l where l.slug = 'conditions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'condition-code', 'code', 'Write code',
  'Write an if statement that prints Ready when score is at least 10.',
  E'if score >= 10:\n    print("Ready")',
  'Use >= for at least.',
  'The condition checks score, then the indented print runs when it is true.',
  4, true
from public.lessons l where l.slug = 'conditions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'loop-range-output', 'choice', 'Predict the output',
  'Which sequence is printed?',
  E'for i in range(3):\n    print(i)',
  '["0, 1, 2","1, 2, 3","0, 1, 2, 3","3, 3, 3"]'::jsonb,
  'range(3) starts at zero and stops before three.',
  'range(3) produces 0, 1 and 2.',
  1, true
from public.lessons l where l.slug = 'loops'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'loop-for-keyword', 'text', 'Fill the keyword',
  'Complete the loop keyword.',
  E'____ item in items:\n    print(item)',
  'Loop keyword',
  'Use the keyword for visiting each item.',
  'for loops once for each item in a collection.',
  2, true
from public.lessons l where l.slug = 'loops'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'loop-while-syntax', 'choice', 'Choose the loop',
  'Which line starts a valid while loop?',
  '["while lives > 0:","while lives > 0","loop lives > 0:","while (lives > 0) then"]'::jsonb,
  'A while condition line also ends with a colon.',
  'while repeats while its condition remains true.',
  3, true
from public.lessons l where l.slug = 'loops'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'loop-code', 'code', 'Write code',
  'Write a loop that prints the numbers 1, 2 and 3 using range.',
  E'for number in range(1, 4):\n    print(number)',
  'Use range(1, 4).',
  'The end value in range is excluded, so range(1, 4) produces 1, 2 and 3.',
  4, true
from public.lessons l where l.slug = 'loops'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, options, hint, explanation, sort_order, is_published
)
select l.id, 'function-def', 'choice', 'Choose the function',
  'Which line correctly defines a function named greet?',
  '["def greet():","function greet():","def greet","greet = function()"]'::jsonb,
  'Python functions begin with def.',
  'A function definition uses def, parentheses and a colon.',
  1, true
from public.lessons l where l.slug = 'functions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, options, hint, explanation, sort_order, is_published
)
select l.id, 'function-parameter-output', 'choice', 'Predict the output',
  'What will this display?',
  E'def greet(name):\n    print(name)\n\ngreet("Maya")',
  '["Maya","name","greet","Nothing"]'::jsonb,
  'Track the value passed into the name parameter.',
  'The string Maya becomes the value of name and is printed.',
  2, true
from public.lessons l where l.slug = 'functions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, code_snippet, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'function-return', 'text', 'Fill the keyword',
  'Which keyword sends a value back from a function?',
  E'def double(number):\n    ____ number * 2',
  'Python keyword',
  'Use the keyword that gives a result back to the caller.',
  'return sends a result back from a function.',
  3, true
from public.lessons l where l.slug = 'functions'
on conflict (exercise_key) do nothing;

insert into public.exercises (
  lesson_id, exercise_key, exercise_type, eyebrow, prompt, placeholder, hint, explanation, sort_order, is_published
)
select l.id, 'function-code', 'code', 'Write code',
  'Write a function named square that returns number multiplied by itself.',
  E'def square(number):\n    return number * number',
  'Define square(number), then return the multiplication.',
  'The parameter receives the value and return sends its square back.',
  4, true
from public.lessons l where l.slug = 'functions'
on conflict (exercise_key) do nothing;

insert into private.exercise_answers (
  exercise_id, accepted_answers, correct_feedback, incorrect_feedback
)
select e.id,
  case e.exercise_key
    when 'hello-print-choice' then '["print(\"Hello, coder!\")"]'::jsonb
    when 'hello-fill-print' then '["print"]'::jsonb
    when 'hello-output' then '["Python is fun"]'::jsonb
    when 'variable-create' then '["score = 10"]'::jsonb
    when 'variable-name' then '["lives"]'::jsonb
    when 'variable-output' then '["7"]'::jsonb
    when 'variable-code' then '["language=\"Python\"","language=''Python''"]'::jsonb
    when 'type-string' then '["String"]'::jsonb
    when 'type-integer' then '["Integer"]'::jsonb
    when 'type-boolean' then '["True"]'::jsonb
    when 'type-float-code' then '["temperature=24.5"]'::jsonb
    when 'operator-add' then '["8"]'::jsonb
    when 'operator-compare' then '["True"]'::jsonb
    when 'operator-multiply' then '["*"]'::jsonb
    when 'operator-code' then '["total=6*4"]'::jsonb
    when 'checkpoint-print' then '["print(\"Ready\")"]'::jsonb
    when 'checkpoint-variable' then '["score = 12"]'::jsonb
    when 'checkpoint-type' then '["Float"]'::jsonb
    when 'checkpoint-operator' then '["7"]'::jsonb
    when 'checkpoint-code' then '["score=12\nprint(score)"]'::jsonb
  end,
  case
    when e.exercise_key like 'hello-%' then 'Correct — you are getting the hang of Python output.'
    else 'Correct — that variable works.'
  end,
  case
    when e.exercise_key like 'hello-%' then 'Look again at how Python prints text.'
    else 'Follow the variable-name = value pattern and try again.'
  end
from public.exercises e
where e.exercise_key in (
  'hello-print-choice',
  'hello-fill-print',
  'hello-output',
  'variable-create',
  'variable-name',
  'variable-output',
  'variable-code',
  'type-string',
  'type-integer',
  'type-boolean',
  'type-float-code',
  'operator-add',
  'operator-compare',
  'operator-multiply',
  'operator-code',
  'checkpoint-print',
  'checkpoint-variable',
  'checkpoint-type',
  'checkpoint-operator',
  'checkpoint-code'
)
on conflict (exercise_id) do nothing;
