create table if not exists public.code_run_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  language text not null,
  created_at timestamptz not null default now(),
  exit_code integer,
  runtime_ms integer,
  constraint code_run_events_language_check
    check (language in ('python', 'javascript'))
);

create index if not exists code_run_events_user_created_idx
  on public.code_run_events(user_id, created_at desc);

alter table public.code_run_events enable row level security;

revoke all privileges on table public.code_run_events from anon, authenticated;
revoke all privileges on sequence public.code_run_events_id_seq from anon, authenticated;

create or replace function public.reserve_code_run(
  p_user_id uuid,
  p_language text,
  p_limit integer default 30
)
returns table (
  event_id bigint,
  remaining integer
)
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  run_count integer;
  new_event_id bigint;
  bounded_limit integer := greatest(1, least(coalesce(p_limit, 30), 100));
begin
  if p_user_id is null then
    raise exception 'user id is required';
  end if;

  if p_language not in ('python', 'javascript') then
    raise exception 'unsupported language';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('code-run:' || p_user_id::text, 0));

  select count(*)::integer
  into run_count
  from public.code_run_events
  where user_id = p_user_id
    and created_at >= now() - interval '1 hour';

  if run_count >= bounded_limit then
    return;
  end if;

  insert into public.code_run_events (user_id, language)
  values (p_user_id, p_language)
  returning id into new_event_id;

  return query
  select new_event_id, greatest(0, bounded_limit - run_count - 1);
end;
$$;

revoke all on function public.reserve_code_run(uuid, text, integer)
from public, anon, authenticated;
grant execute on function public.reserve_code_run(uuid, text, integer)
to service_role;
